name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: DoSomething
      run: |
        sudo apt-get update -yqq
        sudo apt-get install -y qemu-system-x86-64 qemu-guest-agent ovmf mmdebstrap
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        sudo wget -q --output-document /usr/local/bin/vmtest https://github.com/danobi/vmtest/releases/download/v0.17.0/vmtest-x86_64
        sudo chmod a+x /usr/local/bin/vmtest
        /usr/local/bin/vmtest --help
        wget -q https://github.com/danobi/vmtest/releases/download/test_assets/bzImage-v6.6-default
        mmdebstrap sid ./sid --include=neofetch,curl
        vmtest --kernel ./bzImage-v6.6-default --rootfs ./sid "uname -r; cat /etc/os-release; neofetch"
