name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        sudo apt-get update -yqq
        sudo apt-get install -y qemu-system-x86-64 qemu-guest-agent ovmf mmdebstrap debian-archive-keyring
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        sudo wget -q --output-document /usr/local/bin/vmtest https://github.com/danobi/vmtest/releases/download/v0.17.0/vmtest-x86_64
        sudo chmod a+x /usr/local/bin/vmtest
        /usr/local/bin/vmtest --help
        wget -q https://github.com/danobi/vmtest/releases/download/test_assets/bzImage-v6.6-default
        sudo mmdebstrap sid ./sid --include=neofetch,curl,qemu-guest-agent,iproute2,systemd-resolved
        sudo cp /etc/resolv.conf ./sid/etc/resolv.conf

    - name: Run vmtest
      run: |
        set -x
        
        (
        cat <<'EOF'
        #!/bin/bash
        
        id
        uname -a
        cat /etc/os-release

        ip a
        ping 8.8.8.8
        
        EOF
        ) > ./script.sh

        sudo mv script.sh ./sid/script.sh
        sudo chmod a+x ./sid/script.sh
        
        sudo vmtest --kernel ./bzImage-v6.6-default --rootfs ./sid /script.sh
